---
- name: ensure AdoptJDK package repo is configured
  yum_repository:
    name: AdoptOpenJDK
    description: AdoptOpenJDK
    baseurl: http://adoptopenjdk.jfrog.io/adoptopenjdk/rpm/centos/$releasever/$basearch
    enabled: true
    gpgcheck: true
    gpgkey: https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public
    state: present
- name: ensure open JRE 11 is installed
  yum:
    name: "adoptopenjdk-{{ jre_version }}-hotspot-jre"
    state: latest
    